/* eslint-disable @typescript-eslint/no-explicit-any */

import { locales } from "@/i18n";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import { notFound } from "next/navigation";
import Header from "../components/Header";
import "./globals.css";

const geistSans = Geist({ subsets: ["latin"] });
const geistMono = Geist_Mono({ subsets: ["latin"] });

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <div className={bebasNeue.className}>
            <Header />
            {/* Example usage of Bebas Neue */}
            {children}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
